language: php
php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
before_install:
    - php --version
install:
    - make install
before_script:
    - phpenv rehash
script:
    - 'echo "Travis PHP Version: $TRAVIS_PHP_VERSION"'
    - '[[ "${TRAVIS_PHP_VERSION:0:1}" = 7 ]] && make test_php7 || make test_php5'
env:
    global:
        - COMPOSER_OPTIONS='--prefer-source --no-interaction'
